### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by acidjunk** [StackVista/stackpack-sap#12]
https://github.com/StackVista/stackpack-sap/blob/master/LICENSE.md contains info about "DataDog": are you somehow affiliated with DataDog? Or was this repo forked?

Also: a small typo on your github top page: search for "Utretcht"

**Comment by acidjunk** [comment]
The current link to the StackState docs from README seems incorrect.

**Comment by mpvvliet** [comment]
Thanks for pointing that out! We are not affiliated with DataDog, although we forked their agent to bootstrap our own (see https://github.com/StackVista/stackstate-agent). The code in this repository has no relation to DataDog, I will update the license.

**Comment by mpvvliet** [comment]
Also fixed the typo in our organisation.
